#pragma once

const char* script = 
"const tempChart = new Chart(document.getElementById('tempChart'), {"
"  type: 'line',"
"  data: {"
"	labels: [],"
"	datasets: [{"
"	  label: 'Temperatura (°C)',"
"	  data: [],"
"	  borderColor: 'red',"
"	  backgroundColor: 'rgba(255,0,0,0.1)',"
"	  fill: true,"
"	}]"
"  },"
"});"
"const humChart = new Chart(document.getElementById('humChart'), {"
"  type: 'line',"
"  data: {"
"	labels: [],"
"	datasets: [{"
"	  label: 'Umidade (%)',"
"	  data: [],"
"	  borderColor: 'blue',"
"	  backgroundColor: 'rgba(0,0,255,0.1)',"
"	  fill: true,"
"	}]"
"  },"
"});"
"const pressChart = new Chart(document.getElementById('pressChart'), {"
"  type: 'line',"
"  data: {"
"	labels: [],"
"	datasets: [{"
"	  label: 'Pressão (kPa)',"
"	  data: [],"
"	  borderColor: 'green',"
"	  backgroundColor: 'rgba(0,255,0,0.1)',"
"	  fill: true,"
"	}]"
"  },"
""
"});"
""
"const tempRange = document.getElementById('tempRange');"
"const tempMin = document.getElementById('tempMin');"
"const tempMax = document.getElementById('tempMax');"
"const humRange = document.getElementById('humRange');"
"const humMin = document.getElementById('humMin');"
"const humMax = document.getElementById('humMax');"
"const pressRange = document.getElementById('pressRange');"
""
"const tempVal = document.getElementById('tempVal');"
"const humVal = document.getElementById('humVal');"
"const pressVal = document.getElementById('pressVal');"
""
"function getParams() {"
"	fetch('params').then(res => res.json()).then(data => {"
"		tempRange.value = data.offsetTemp;"
"		tempVal.textContent = data.offsetTemp;"
"		tempMin.value = data.minTemp;"
"		tempMax.value = data.maxTemp;"
"		humRange.value = data.offsetHum;"
"		humVal.textContent = data.offsetHum;"
"		humMin.value = data.minHum;"
"		humMax.value = data.maxHum;"
"		pressRange.value = data.offsetPre;"
"		pressVal.textContent = data.offsetPre;"
"	});"
"}"
""
"function saveParams() {"
"  tempVal.textContent = tempRange.value;"
"  humVal.textContent = humRange.value;"
"  pressVal.textContent = pressRange.value;"
"  fetch(`"
"	params?"
"	minTemp=${tempMin.value}&maxTemp=${tempMax.value}&offsetTemp=${tempRange.value}&"
"	minHum=${humMin.value}&maxHum=${humMax.value}&offsetHum=${humRange.value}&"
"	offsetPre=${pressRange.value}"
"  `);"
"}"
""
"function updateData() {"
"  const time = getTimeLabel();"
"  fetch('data').then(res => res.json()).then(data => {"
"	addData(tempChart, time, parseFloat(data.temperature));"
"	addData(humChart, time, parseFloat(data.humidity));"
"	addData(pressChart, time, parseFloat(data.pressure));"
"  });"
"}"
""
"function getTimeLabel() {"
"  const now = new Date();"
"  return now.getHours().toString().padStart(2, '0') + ':' +"
"		 now.getMinutes().toString().padStart(2, '0') + ':' +"
"		 now.getSeconds().toString().padStart(2, '0');"
"}"
""
"function addData(chart, label, data) {"
"  if (chart.data.labels.length >= 100) {"
"	chart.data.labels.shift();"
"	chart.data.datasets[0].data.shift();"
"  }"
"  chart.data.labels.push(label);"
"  chart.data.datasets[0].data.push(data);"
"  chart.update();"
"}"
""
"getParams();"
"setInterval(updateData, 2000);";